# Generated by Django 3.2.4 on 2021-07-13 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='author_name',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='form',
            name='book_name',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
