# Generated by Django 3.2.4 on 2021-07-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Books', '0002_auto_20210713_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
